"""add_ingridients

Revision ID: 07527b634308
Revises: f41d12db65bf
Create Date: 2023-06-11 17:21:51.844891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07527b634308'
down_revision = 'f41d12db65bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
