"""Init

Revision ID: f41d12db65bf
Revises: bd1affdbac67
Create Date: 2023-06-10 11:43:06.752725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f41d12db65bf"
down_revision = "bd1affdbac67"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("tg_id", sa.String(), nullable=False),
        sa.Column("tg_username", sa.String(), nullable=True),
        sa.Column("tg_first_name", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
